"""Create association table for blog likes.

Revision ID: 0fe9c1987695
Revises: 8b3c61c531f5
Create Date: 2025-08-12 10:54:20.688764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe9c1987695'
down_revision: Union[str, Sequence[str], None] = '8b3c61c531f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('blog_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'blog_id'),
    sa.UniqueConstraint('user_id', 'blog_id', name='unique_user_blog_like')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_likes')
    # ### end Alembic commands ###
